version: '3'
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    user: root
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  static:
    build:
      context: infra/nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  db-volume:
  public-data:
  tmp-data:
  log-data: