default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DB_PASSWORD"] %>
  host: db

development:
 <<: *default
 database: dev_database

test:
 <<: *default
 database: test_database

production:
  <<: *default
  database: learn-community_production
  username: root
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:hostname] %>
